name: coverage
on: [push, pull_request]

jobs:
  coverage:
    strategy:
      matrix:
        go-version: [~1.17, ^1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: tests
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test -race -covermode=atomic -coverprofile=./coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.out
